[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10"
prost = "0.12"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

fern = "0.6"
log = "0.4"

[build-dependencies]
tonic-build = "0.10"