[package]
name = "remini"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false

[profile.dev]
opt-level = 0
debug = true

[dependencies]
tonic = "0.10"
prost = "0.12"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

image_processor = { git = "https://github.com/Gravitalia/Autha.git", package = "image_processor" }
image = "0.24"
tract-onnx = "0.21"
anyhow = "1"

fern = "0.6"
log = "0.4"

[build-dependencies]
tonic-build = "0.10"